version: '3'

services:
  nethack4-server:
    build: ./nethack4-server/
    depends_on:
      - db
    ports:
      - 53430:53430
    volumes:
      - ./.saves:/opt/nethack4/bin/save
  db:
    build: ./db/
    volumes:
      - ./.data:/var/lib/postgresql/data
